kind: Pod
apiVersion: v1
metadata:
  name: task-pv-pod
  labels:
    appname: pvpod

spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
       claimName: task-pv-claim
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: task-pv-storage
---
apiVersion: v1
kind: Service
metadata:
  name: svc-to-pvc
spec:
  selector:
    appname: pvpod
  type: NodePort
  ports:
  - port: 80

