apiVersion: batch/v1
kind: CronJob
metadata:
  name: quakewatch-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: quakewatch-cron
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from QuakeWatch CronJob
          restartPolicy: OnFailure
